"use client";

import { useState } from "react";
import { PDFDocument } from "pdf-lib";

export default function PDFMetadataPage() {
  const [file,setFile]=useState<File|null>(null),[title,setTitle]=useState(""),[author,setAuthor]=useState(""),[subject,setSubject]=useState(""),[keywords,setKeywords]=useState(""),[processing,setProcessing]=useState(false),[message,setMessage]=useState("");
  const save=async()=>{if(!file)return setMessage("Please select a PDF file.");try{setProcessing(true);setMessage("");const pdf=await PDFDocument.load(await file.arrayBuffer());pdf.setTitle(title);pdf.setAuthor(author);pdf.setSubject(subject);pdf.setKeywords(keywords.split(",").map(x=>x.trim()).filter(Boolean));const out=await pdf.save();const url=URL.createObjectURL(new Blob([out as BlobPart],{type:"application/pdf"}));const a=document.createElement("a");a.href=url;a.download="kaamkitpro-metadata.pdf";document.body.appendChild(a);a.click();a.remove();URL.revokeObjectURL(url);setMessage("PDF metadata updated successfully.");}catch(e){console.error(e);setMessage("Could not update the PDF metadata.");}finally{setProcessing(false);}};
  return <main className="min-h-screen bg-slate-50 px-4 py-10"><div className="mx-auto max-w-3xl"><a href="/tools/pdf" className="text-sm font-medium text-blue-600 hover:underline">← Browse all PDF tools</a><div className="mt-4 rounded-2xl bg-white p-6 shadow-sm md:p-8"><div className="mb-8 text-center"><h1 className="text-3xl font-bold text-slate-900">PDF Metadata Editor</h1><p className="mt-3 text-slate-600">Edit title, author, subject and keywords inside a PDF.</p></div><div className="rounded-xl border-2 border-dashed border-slate-300 bg-slate-50 p-8 text-center"><input id="pdf-file" type="file" accept=".pdf,application/pdf" className="hidden" onChange={e=>{setFile(e.target.files?.[0]||null);setMessage("");e.target.value="";}}/><label htmlFor="pdf-file" className="inline-block cursor-pointer rounded-lg bg-blue-600 px-6 py-3 font-semibold text-white hover:bg-blue-700">Select PDF</label></div>{file&&<div className="mt-6 space-y-4 rounded-xl border border-slate-200 p-5"><p className="font-medium text-slate-900">{file.name}</p>{[["title","Title",title,setTitle],["author","Author",author,setAuthor],["subject","Subject",subject,setSubject],["keywords","Keywords (comma separated)",keywords,setKeywords]].map(([id,label,value,setter])=><div key={String(id)}><label htmlFor={String(id)} className="text-sm font-medium text-slate-700">{String(label)}</label><input id={String(id)} value={String(value)} onChange={e=>(setter as (v:string)=>void)(e.target.value)} className="mt-2 w-full rounded-lg border border-slate-300 px-4 py-3 text-slate-900"/></div>)}<button type="button" onClick={save} disabled={processing} className="w-full rounded-lg bg-blue-600 px-6 py-3 font-semibold text-white hover:bg-blue-700 disabled:opacity-50">{processing?"Saving...":"Save Metadata & Download"}</button></div>}{message&&<div className="mt-6 rounded-lg bg-slate-100 p-4 text-center text-sm text-slate-700">{message}</div>}<p className="mt-8 text-center text-xs text-slate-500">Your PDF is processed directly in your browser.</p></div></div></main>;
}