"use client";

import { useState } from "react";
import { PDFDocument, StandardFonts, rgb, degrees } from "pdf-lib";

export default function PDFWatermarkPage() {
  const [file,setFile]=useState<File|null>(null), [text,setText]=useState("CONFIDENTIAL"), [processing,setProcessing]=useState(false), [message,setMessage]=useState("");
  const apply=async()=>{if(!file)return setMessage("Please select a PDF file.");try{setProcessing(true);setMessage("");const pdf=await PDFDocument.load(await file.arrayBuffer());const font=await pdf.embedFont(StandardFonts.HelveticaBold);pdf.getPages().forEach(p=>{const {width,height}=p.getSize();const size=Math.min(width,height)/7;const w=font.widthOfTextAtSize(text,size);p.drawText(text,{x:(width-w)/2,y:(height-size)/2,size,font,color:rgb(.65,.65,.68),opacity:.22,rotate:degrees(45)});});const out=await pdf.save();const url=URL.createObjectURL(new Blob([out as BlobPart],{type:"application/pdf"}));const a=document.createElement("a");a.href=url;a.download="kaamkitpro-watermarked.pdf";document.body.appendChild(a);a.click();a.remove();URL.revokeObjectURL(url);setMessage("Watermark added successfully.");}catch(e){console.error(e);setMessage("Could not process this PDF. Please make sure it is valid.");}finally{setProcessing(false);}};
  return <main className="min-h-screen bg-slate-50 px-4 py-10"><div className="mx-auto max-w-3xl"><a href="/tools/pdf" className="text-sm font-medium text-blue-600 hover:underline">← Browse all PDF tools</a><div className="mt-4 rounded-2xl bg-white p-6 shadow-sm md:p-8"><div className="mb-8 text-center"><h1 className="text-3xl font-bold text-slate-900">PDF Watermark Tool</h1><p className="mt-3 text-slate-600">Add a simple text watermark to every PDF page in your browser.</p></div><div className="rounded-xl border-2 border-dashed border-slate-300 bg-slate-50 p-8 text-center"><input id="pdf-file" type="file" accept=".pdf,application/pdf" className="hidden" onChange={e=>{setFile(e.target.files?.[0]||null);setMessage("");e.target.value="";}}/><label htmlFor="pdf-file" className="inline-block cursor-pointer rounded-lg bg-blue-600 px-6 py-3 font-semibold text-white hover:bg-blue-700">Select PDF</label><p className="mt-3 text-sm text-slate-500">Choose one PDF file.</p></div>{file&&<div className="mt-6 rounded-xl border border-slate-200 p-5"><p className="font-medium text-slate-900">{file.name}</p><label htmlFor="watermark" className="mt-5 block text-sm font-medium text-slate-700">Watermark text</label><input id="watermark" value={text} onChange={e=>setText(e.target.value)} maxLength={40} className="mt-2 w-full rounded-lg border border-slate-300 px-4 py-3 text-slate-900"/><button type="button" onClick={apply} disabled={processing||!text.trim()} className="mt-5 w-full rounded-lg bg-blue-600 px-6 py-3 font-semibold text-white hover:bg-blue-700 disabled:opacity-50">{processing?"Adding watermark...":"Add Watermark & Download"}</button></div>}{message&&<div className="mt-6 rounded-lg bg-slate-100 p-4 text-center text-sm text-slate-700">{message}</div>}<p className="mt-8 text-center text-xs text-slate-500">Your PDF is processed directly in your browser.</p></div></div></main>;
}