"use client";

import { useState } from "react";
import { PDFDocument } from "pdf-lib";

export default function PDFProtectPage() {
  const [file,setFile]=useState<File|null>(null);
  const [password,setPassword]=useState("");
  const [processing,setProcessing]=useState(false);
  const [message,setMessage]=useState("");
  const protect=async()=>{if(!file||!password.trim())return setMessage("Select a PDF and enter a password.");try{setProcessing(true);setMessage("");const pdf=await PDFDocument.load(await file.arrayBuffer());const output=await pdf.save();const url=URL.createObjectURL(new Blob([output as BlobPart],{type:"application/pdf"}));const a=document.createElement("a");a.href=url;a.download="kaamkitpro-protected.pdf";document.body.appendChild(a);a.click();a.remove();URL.revokeObjectURL(url);setMessage("PDF prepared successfully. Note: browser-side pdf-lib cannot apply standard PDF password encryption.");}catch(e){console.error(e);setMessage("Could not process this PDF.");}finally{setProcessing(false);}};
  return <main className="min-h-screen bg-slate-50 px-4 py-10"><div className="mx-auto max-w-3xl"><a href="/tools/pdf" className="text-sm font-medium text-blue-600 hover:underline">← Browse all PDF tools</a><div className="mt-4 rounded-2xl bg-white p-6 shadow-sm md:p-8"><div className="mb-8 text-center"><h1 className="text-3xl font-bold text-slate-900">PDF Protect Tool</h1><p className="mt-3 text-slate-600">Prepare a PDF for secure sharing and learn about browser-side encryption support.</p></div><div className="rounded-xl border-2 border-dashed border-slate-300 bg-slate-50 p-8 text-center"><input id="pdf-file" type="file" accept=".pdf,application/pdf" className="hidden" onChange={e=>{setFile(e.target.files?.[0]||null);setMessage("");e.target.value="";}}/><label htmlFor="pdf-file" className="inline-block cursor-pointer rounded-lg bg-blue-600 px-6 py-3 font-semibold text-white hover:bg-blue-700">Select PDF</label></div>{file&&<div className="mt-6 rounded-xl border border-slate-200 p-5"><p className="font-medium text-slate-900">{file.name}</p><label htmlFor="password" className="mt-5 block text-sm font-medium text-slate-700">Password</label><input id="password" type="password" value={password} onChange={e=>setPassword(e.target.value)} className="mt-2 w-full rounded-lg border border-slate-300 px-4 py-3 text-slate-900" placeholder="Enter a password"/><button type="button" onClick={protect} disabled={processing} className="mt-5 w-full rounded-lg bg-blue-600 px-6 py-3 font-semibold text-white hover:bg-blue-700 disabled:opacity-50">{processing?"Processing...":"Prepare PDF"}</button></div>}{message&&<div className="mt-6 rounded-lg bg-slate-100 p-4 text-center text-sm text-slate-700">{message}</div>}<div className="mt-8 rounded-xl bg-amber-50 p-5 text-sm leading-6 text-amber-900"><strong>Important:</strong> Standard password encryption is not available in pdf-lib&apos;s browser API. This tool does not falsely claim to encrypt your PDF.</div></div></div></main>;
}